from pydantic import BaseModel
from typing import Optional


class ResearchReport(BaseModel):
    ticker: str
    company_name: Optional[str] = None
    peers_analyzed: Optional[list[str]] = None
    generated_at: Optional[str] = None
    summary: Optional[str] = None
    fundamental_analysis: Optional[str] = None
    technical_analysis: Optional[str] = None
    peer_comparison: Optional[str] = None
    strengths: Optional[list[str]] = None
    risks: Optional[list[str]] = None
    data_gaps: Optional[list[str]] = None
    disclaimer: str = (
        "This report is generated by an AI system for educational purposes only. "
        "It does not constitute financial advice or a recommendation to buy or sell any security."
    )
